[package]
name = "renderer"
version = "0.1.0"
authors = ["Slide-rs Developers"]

[examples]

[dependencies]
pulse="*"
gfx="*"
gfx_device_gl="*"
cgmath="*"
draw_queue="*"
gfx_phase="*"
gfx_scene="0.3.0"
gfx_pipeline="0.2.1"

[dependencies.slide-rs-engine]
git = "https://github.com/csherratt/engine.git"

[dependencies.entity]
git = "https://github.com/csherratt/entity.git"

[dependencies.transform]
git = "https://github.com/csherratt/transform.git"

[dependencies.graphics]
git = "https://github.com/csherratt/graphics.git"

[dependencies.scene]
git = "https://github.com/csherratt/scene.git"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/slide-rs/fibe-rs.git"

[dev-dependencies.future_pulse]
git = "https://github.com/csherratt/future_pulse.git"

[dev-dependencies.parent]
git = "https://github.com/csherratt/parent.git"

[dev-dependencies.no_clip]
git = "https://github.com/csherratt/no_clip.git"

[dev-dependencies.std_graphics]
git = "https://github.com/whiske-rs/std_graphics.git"

