[package]
name = "std_graphics"
version = "0.1.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[dependencies]
cgmath="*"
genmesh="*"
pulse="*"

[dependencies.entity]
git = "https://github.com/csherratt/entity.git"

[dependencies.graphics]
git = "https://github.com/csherratt/graphics.git"

[dependencies.fibe]
git = "https://github.com/slide-rs/fibe-rs.git"

[dependencies.future_pulse]
git = "https://github.com/slide-rs/future_pulse.git"
