[package]
name = "renderer"
version = "0.1.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[examples]

[dependencies]
pulse="*"

[dependencies.snowmew-engine]
git = "https://github.com/snowmew/engine.git"

[dependencies.entity]
git = "https://github.com/snowmew/entity.git"

[dependencies.position]
git = "https://github.com/snowmew/position.git"

[dependencies.graphics]
git = "https://github.com/snowmew/graphics.git"

[dependencies.scene]
git = "https://github.com/snowmew/scene.git"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/kvark/fibe-rs.git"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs.git"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl.git"

[dependencies.draw_queue]
git = "https://github.com/gfx-rs/gfx_scene.git"

[dependencies.gfx_phase]
git = "https://github.com/gfx-rs/gfx_scene.git"

[dependencies.gfx_scene]
git = "https://github.com/gfx-rs/gfx_scene.git"

[dependencies.gfx_pipeline]
git = "https://github.com/csherratt/gfx_pipeline"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs.git"

[dev-dependencies.parent]
git = "https://github.com/snowmew/parent.git"

[dev-dependencies]
genmesh = "*"
