[package]
name = "snowmew-engine"
version = "0.1.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[lib]
name = "engine"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/kvark/fibe-rs.git"

[dependencies.gfx_window_glutin]
git = "https://github.com/gfx-rs/gfx_window_glutin.git"

[dependencies.gfx]
git = "https://github.com/gfx-rs/gfx-rs.git"

[dependencies.gfx_device_gl]
git = "https://github.com/gfx-rs/gfx_device_gl.git"

[dependencies.glutin]
git = "https://github.com/tomaka/glutin"
