[package]
name = "position"
version = "0.1.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[dependencies]
pulse="*"

[dependencies.entity]
git = "https://github.com/snowmew/entity.git"

[dependencies.parent]
git = "https://github.com/snowmew/parent.git"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/kvark/fibe-rs.git"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs.git"

