[package]
name = "renderer"
version = "0.1.0"
authors = ["Slide-rs Developers"]

[examples]

[dependencies]
pulse="*"
gfx="*"
gfx_device_gl="*"
cgmath="*"
draw_queue="*"
gfx_phase="*"
gfx_scene="*"
gfx_pipeline="*"


[dependencies.slide-rs-engine]
git = "https://github.com/slide-rs/engine.git"

[dependencies.entity]
git = "https://github.com/slide-rs/entity.git"

[dependencies.position]
git = "https://github.com/slide-rs/position.git"

[dependencies.graphics]
git = "https://github.com/slide-rs/graphics.git"

[dependencies.scene]
git = "https://github.com/slide-rs/scene.git"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/slide-rs/fibe-rs.git"

[dev-dependencies.parent]
git = "https://github.com/slide-rs/parent.git"

[dev-dependencies]
genmesh = "*"
