[package]
name = "whiske"
version = "0.1.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[dependencies]
glutin="*"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/slide-rs/fibe-rs.git"

[dependencies.entity]
git = "https://github.com/csherratt/entity.git"

[dependencies.whiske-rs-engine]
path = "src/engine"
version = "*"

[dependencies.whiske-rs-parent]
path = "src/parent"
version = "*"
