[package]
name = "graphics"
version = "0.1.0"
authors = ["Colin Sherratt <colin.sherratt@gmail.com>"]

[dependencies]
pulse="*"
gfx="*"
image="*"

[dependencies.entity]
git = "https://github.com/csherratt/entity.git"

[dependencies.parent]
git = "https://github.com/csherratt/parent.git"

[dependencies.snowstorm]
git = "https://github.com/csherratt/snowstorm.git"

[dependencies.fibe]
git = "https://github.com/slide-rs/fibe-rs.git"

[dependencies.future_pulse]
git = "https://github.com/csherratt/future_pulse.git"

